M48
; DRILL file {KiCad 7.0.9} date Wed Jan  3 20:39:35 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-03T20:39:35+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C3.200
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C4.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C5.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T6C5.300
%
G90
G05
T1
X187.96Y-132.08
T2
X194.056Y-131.572
T3
X200.66Y-131.064
T4
X208.788Y-130.048
T6
X218.44Y-129.032
T5
X107.024Y-114.0G85X107.024Y-124.0
G05
T0
M30
